# Generated by Django 2.1.3 on 2018-12-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181202_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_boss',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_parent',
        ),
    ]
