# Generated by Django 2.1.3 on 2018-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181202_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
