# Generated by Django 2.1.3 on 2018-12-05 13:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='person.Person')),
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='person.Person')),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='person.Person')),
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('person.person',),
        ),
    ]
