# Generated by Django 2.1.3 on 2018-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_admin_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
