# Generated by Django 2.1.3 on 2018-12-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181207_1523'),
        ('person', '0004_student_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='history',
            field=models.ForeignKey(null=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='main.History'),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(to='person.Student'),
        ),
    ]
