# Generated by Django 2.1.3 on 2018-12-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181207_1523'),
        ('person', '0007_auto_20181208_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
    ]
