# Generated by Django 2.1.3 on 2018-12-08 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_admin_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
    ]
