# Generated by Django 2.1.3 on 2018-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20181209_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('NORM', 'ปกติ'), ('PROB', 'ผิดปกติ')], default='NORM', max_length=4),
        ),
    ]
