# Generated by Django 2.1.3 on 2018-12-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_remove_admin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='test',
        ),
    ]
