# Generated by Django 2.1.3 on 2018-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_remove_admin_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, default='test', max_length=10),
        ),
    ]
