# Generated by Django 2.1.3 on 2018-12-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_auto_20181210_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
    ]
