# Generated by Django 2.1.3 on 2018-12-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_remove_admin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
