# Generated by Django 2.1.3 on 2018-12-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20181210_0001'),
        ('person', '0029_auto_20181210_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
    ]
