# Generated by Django 2.1.3 on 2018-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('INBUS', 'อยู่ในรถ'), ('DNCARE', 'กลับเอง'), ('ARRIVE', 'ถึงแล้ว'), ('PROB', 'ผิดปกติ')], default='DNCARE', max_length=6),
        ),
    ]
