# Generated by Django 2.1.3 on 2018-12-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_bus_teacher'),
        ('person', '0032_auto_20181215_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
