# Generated by Django 2.1.3 on 2018-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_auto_20181216_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scan_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
