# Generated by Django 2.1.3 on 2018-12-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0034_student_scan_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='scan_count',
        ),
    ]
