# Generated by Django 2.1.3 on 2018-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0037_remove_student_bag_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bag_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
