# Generated by Django 2.1.3 on 2018-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0039_student_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.IntegerField(blank=True, default=40),
        ),
    ]
