# Generated by Django 2.1.3 on 2018-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0040_student_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, default=40),
        ),
    ]
