# Generated by Django 2.1.3 on 2018-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0041_auto_20181216_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bag_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
