# Generated by Django 2.1.3 on 2018-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('state_province', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='history',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='history',
            name='student',
        ),
        migrations.RemoveField(
            model_name='history',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('ON', 'Get_on'), ('DEP', 'Depart'), ('OFF', 'Get_off')], max_length=3),
        ),
    ]
