# Generated by Django 2.1.3 on 2018-12-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_admin_parent'),
        ('main', '0002_auto_20181206_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Student'),
        ),
    ]
