# Generated by Django 2.1.3 on 2018-12-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181206_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
    ]
