# Generated by Django 2.1.3 on 2018-12-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
    ]
