# Generated by Django 2.1.3 on 2018-12-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
    ]
