# Generated by Django 2.1.3 on 2018-12-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_student_key'),
        ('main', '0009_bus_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='history',
            name='teacher',
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Teacher'),
        ),
        migrations.AddField(
            model_name='history',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Bus'),
        ),
    ]
