# Generated by Django 2.1.3 on 2018-12-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181206_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.IntegerField(blank=True),
        ),
    ]
