# Generated by Django 2.1.3 on 2018-12-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181207_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
