# Generated by Django 2.1.3 on 2018-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181209_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_speed',
            field=models.IntegerField(default=0),
        ),
    ]
