# Generated by Django 2.1.3 on 2018-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181209_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTV', 'กำลังใช้งาน'), ('STAY', 'จอด'), ('ACCI', 'เกิดอุบัติเหตุ')], default='ACTV', max_length=4),
        ),
    ]
