# Generated by Django 2.1.3 on 2018-12-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181209_2308'),
        ('main', '0015_auto_20181210_0000'),
    ]

    operations = [
    ]
