# Generated by Django 2.1.3 on 2018-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20181210_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTV', 'กำลังใช้งาน'), ('STAY', 'จอด'), ('ACCI', 'เกิดอุบัติเหตุ')], default='ACTV', max_length=4, null=True),
        ),
    ]
