# Generated by Django 2.1.3 on 2018-12-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181214_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='avg_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='max_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTV', 'กำลังใช้งาน'), ('STAY', 'จอด'), ('ACCI', 'เกิดอุบัติเหตุ')], default='STAY', max_length=4),
        ),
    ]
