# Generated by Django 2.1.3 on 2018-12-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20181214_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='teacher',
        ),
    ]
